stages:
  - build
  - deploy

compile_pdf:
  stage: build
  image: timnn/texlive
  script: cd docs && pdflatex main.tex
  artifacts:
    paths:
      - docs/main.pdf

pages:
  stage: deploy
  artifacts:
    paths:
      - docs
  only:
    - main

