name: Build and Deploy PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Compile PDF
      uses: xu-cheng/latex-action@v3
      with:
        root_file: docs/main.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: main-pdf
        path: docs/main.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Download PDF artifact
      uses: actions/download-artifact@v2
      with:
        name: main-pdf
        path: public
